version: "3.8"

services:

  db:
    image: postgres:13
    container_name: db
    ports:
      - 5430:5432
    env_file:
      - vars.env
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data/
    networks:
      - social-network
    logging:
      driver: "json-file"
      options:
          max-size: "50m"


networks:
  social-network:
    external: true