# Generated by Django 3.1.6 on 2021-02-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_api_access_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_api_access_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
