NUMBER_OF_USERS = 2
MAX_POSTS_PER_USER = 3
MAX_LIKES_PER_USER = 3

USER_DEFAULT_PASSWORD = 'Qwerty1!'

ANALYTICS_DATE_FROM = "2021-02-01"
ANALYTICS_DATE_TO = "2021-02-25"

API_HOST = 'http://127.0.0.1/'

API_ENDPOINT_SIGNUP = API_HOST + "api/user/create/"
API_ENDPOINT_LOGIN = API_HOST + "api/user/auth/"
API_ENDPOINT_ADD_POST = API_HOST + "api/post/"
API_ENDPOINT_LIKE_POST = API_HOST + "api/post/like/"
API_ENDPOINT_ANALYTICS = API_HOST + "api/analytics/"

assert NUMBER_OF_USERS > 0
assert MAX_POSTS_PER_USER > 0
assert MAX_LIKES_PER_USER > 0
